apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lp.fullname" . }}
data:
{{- range $path, $_ := .Files.Glob "config/*" }}
{{ printf "%s: |-" $path | trimPrefix "config/" | indent 2 }}
{{ $.Files.Get $path | indent 4 }}
{{- end }}
