Template:
  Theme: "light" # https://primer.style/css/support/theming#set-a-theme
  Pages:
    - Name: Main # A page name will be visible on rendered lp
      IsIndex: True # Marks this page to be index.html
      Headings:
        - Name: Github Repos
          Links:
          - Name: Kubernetes # A singe link
            Url: https://github.com/kubernetes/kubernetes
          - Name: harbor
            Url: https://github.com/goharbor/harbor
          - Name: Container Tools # a dropdown set of links that will appear in heading "Container Tools"
            Urls: 
              - cosign: https://github.com/sigstore/cosign
              - crane: https://github.com/google/go-containerregistry/
              - syft: https://github.com/anchore/syft
              - grype: https://github.com/anchore/grype 
              - cst: https://github.com/GoogleContainerTools/container-structure-test
              - ko: https://github.com/google/ko
        - Name: LP Links!
          Links:
          - Name: Github Primer CSS
            Url: https://primer.style/css/support/theming
          - Name: GH Pages docs
            Url: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
          - 
        - Name: My Personal Projects
          Links:
          - Name: LP
            Url: https://github.com/rjbrown57/lp
          - Name: Binextractor
            Url: https://github.com/rjbrown57/binextractor
        - Name: Tools
          Links:
          - Name: Grafana
            Url: https://github.com/grafana/grafana
          - Name: Prometheus
            Url: https://github.com/prometheus
          - Name: kernel.org
            Url: https://kernel.org/
    - Name: secondpage
      Headings:
        - Name: Github Repos
          Links:
          - Name: Kubernetes
            Url: https://github.com/kubernetes/kubernetes
          - Name: harbor
            Url: https://github.com/goharbor/harbor
          - Name: Container Tools
            Urls: 
              - cosign: https://github.com/sigstore/cosign
              - crane: https://github.com/google/go-containerregistry/
              - syft: https://github.com/anchore/syft
              - grype: https://github.com/anchore/grype 
              - cst: https://github.com/GoogleContainerTools/container-structure-test
              - ko: https://github.com/google/ko
        - Name: My Personal Projects
          Links:
          - Name: LP
            Url: https://github.com/rjbrown57/lp
          - Name: Binextractor
            Url: https://github.com/rjbrown57/binextractor
        - Name: Tools
          Links:
          - Name: Grafana
            Url: https://github.com/grafana/grafana
          - Name: Prometheus
            Url: https://github.com/prometheus
          - Name: kernel.org
            Url: https://kernel.org/
